USE students; 
CREATE TABLE myusers 
(
    ID INTEGER PRIMARY KEY auto_increment,
    UNAME VARCHAR(255) NOT NULL,
    UADDRESS VARCHAR(255) NOT NULL, 
    CLASS VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    -- RECORD_ENTRY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
